#!/usr/bin/env bash

# vcli internal variables
declare SCRIPTNAME
SCRIPTNAME="$(basename "$0")"
declare VERBOSE="no"
declare DEBUG="no"
declare DEBUG_HEXDUMP="no"
declare DEBUGFILE="/tmp/vcli.debug"
declare TMP="/tmp"
declare is_command cmd cmd_history restcmd key len pos history_index
declare -a mounted_paths
declare timeout="2" # timeout to verify connection to Vault
declare http_code
declare vault_host vault_port vault_token current_pwd

# History related vars
declare VCLISTORY="$HOME/.vclistory"
declare pri_suffix="_principal"
declare crt_suffix="_crt"
declare key_suffix="_key"
declare SEARCHIST ENDHIST ADDTMPCMD search_cmd
declare -a cmd_history tmp_history

# vcli dependencies
declare DEPENDENCIES="curl jq"

# COLOURS
TAB=$(tput setaf 4; tput bold)
RED="$(tput setaf 1; tput bold)"
GREEN="$(tput setaf 2; tput bold)"
YELLOW="$(tput setaf 3)"
CYAN="$(tput setaf 6; tput bold)"
NONE="$(tput sgr0)"
BOLD="$(tput bold)"

# Check dependencies
function check_dependency(){
    local dependencies
    dependencies=$*
    for dependency in $dependencies; do
        if ! command -v "$dependency" >/dev/null; then
            echo "$SCRIPTNAME: command '$dependency' not found"
            exit 1
        fi
    done
}

function check_connectivity(){
    if ! timeout $timeout bash -c "</dev/tcp/$vault_host/$vault_port"; then
        echo "Cannot establish connection to $protocol://$vault_host:$vault_port"
        exit 1
    fi
}

# Print prompt
function prompt(){
    local COLOUR=$CYAN
    debug "prompt: http_code=$http_code"
    if [[ $http_code =~ ^2 ]]; then
        COLOUR=$GREEN
    elif [[ $http_code =~ ^3 ]]; then
        COLOUR=$YELLOW
    elif [[ $http_code =~ ^4 ]] || [[ $http_code =~ ^5 ]]; then
        COLOUR=$RED
    fi
    echo -n "[$COLOUR$http_code$NONE] $BOLD$SCRIPTNAME$TAB@$NONE$BOLD$vault_host$TAB:$NONE$BOLD$vault_port$current_pwd$TAB >$NONE "
}

function debug(){
    local msg="$*"
    if [[ $DEBUG == "yes" ]]; then
        echo -e "$msg" >> $DEBUGFILE
    fi
}

################################################# CLI FUNCTIONS #################################################

# return whether is a command or not
function is_cmd(){
    local cmd="$1"
    case $cmd in
        mount*|umount*|cd*|ls*|tree*|cptree*|rmtree*|backup|restore*|cat*|cp*|getcert*|certinfo*|getkrb*|krbinfo*|mv*|put*|rm*|exit*|help*|history|enable-debug|disable-debug|enable-hexdump-debug|disable-hexdump-debug) : ;;
        ""|*) return 1;;
    esac
}

# complete command
function completion(){
    debug "run completion"
    local -a tmparray
    local found _cmd _path _args _secret paths
    local commands=( "mount" "umount" "cd" "ls" "tree" "cptree" "rmtree" "backup" "restore" "cat" "cp" "getcert" "certinfo" "getkrb" "krbinfo" "mv" "put" "rm" "exit" "help" "history" "enable-debug" "disable-debug" "enable-hexdump-debug" "disable-hexdump-debug" )
    IFS=' ' read _cmd _path _args< <(echo "$@")
    debug "cmd: $_cmd, path: $_path"
    # complete command
    if [[ ! $_path ]]; then
        if ! is_cmd "$_cmd" || [[ ! $_cmd =~ \ $ ]]; then
            for c in "${commands[@]}"; do
                if [[ $c =~ ^$_cmd ]]; then
                    debug "found: $c"
                    tmparray+=( $c )
                fi
            done
            found=${#tmparray[@]}
            debug "commands_found $found: " "${tmparray[@]}"
            if [[ $found == 2 ]]; then
                cmd="$(printf "%s\n%s\n" "${tmparray[0]}" "${tmparray[1]}" | sed -e 'N;s/^\(.*\).*\n\1.*$/\1/')"
            elif [[ $found == 1 ]]; then
                cmd="${tmparray[0]} "
            fi
        fi
    # complete path
    else
        debug "searching path $_path"
        _secret=${_path##*/}
        debug "1 path: $_path, secret: $_secret"
        if [[ $_path != $_secret ]]; then
            _path=${_path%$_secret*}
        else
            unset _path
        fi
        debug "2 path: $_path, secret: $_secret"
        if [[ ! $_path ]] || [[ $_path == "/" ]]; then
            paths=$(_ls "$_path" | grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
        # if $url is other than root
        else
            paths=$(_ls "$_path" | jq '.data .keys' |grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
        fi
        backIFS=$IFS
        IFS=$' '
        for p in $paths; do
            if [[ $p =~ ^$_secret ]]; then
                debug "found path: $p"
                tmparray+=( $p )
            fi
        done
        IFS=$backIFS
        found=${#tmparray[@]}
        debug "paths_found $found: " "${tmparray[@]}"
        debug "cmd: $_cmd $_path"
        local tmpath_so_far path_so_far
        if [[ $found == 1 ]]; then
            cmd="$_cmd $_path${tmparray[0]}"
            debug "new_cmd2: $cmd"
        elif [[ $found -gt 1 ]]; then
            echo
            for p in "${tmparray[@]}"; do
                echo "$p" | sed -e "s/\//$CYAN\/$NONE/"
            done
            local n=1
            local i=0
            # compare all found occurrences and build the common substring
            while true ; do
                tmpath_so_far=${tmparray[$i]::$n}
                debug "tmpath_so_far: $tmpath_so_far"
                while [[ $i -lt ${#tmparray[@]} ]]; do
                    debug "pathmatch: i=$i n=$n ${tmparray[$i]::$n} == $tmpath_so_far"
                    if [[ ${tmparray[$i]::$n} != $tmpath_so_far ]]; then
                        end="true"
                        break 2
                    fi
                    tmpath_so_far=${tmparray[$i]::$n}
                    let i++
                done
                if [[ ! $end ]]; then
                    path_so_far=$tmpath_so_far
                    debug "pathsofar: $path_so_far"
                fi
                let n++
                let i=0
            done
            cmd="$_cmd $_path$path_so_far"
            debug "new_cmd1: $cmd"
            unset tmparray tmpath_so_far path_so_far end
            prompt
            return 1
        fi
    fi
    unset tmparray found
}

# add $cmd to command history @cmd_history
function add_cmd(){
    local cmd
    cmd="$(echo "$*" | sed -e "s/^[[:space:]]\+\(.*\)/\1/g" -e "s/[[:space:]]\+$//g" | tr -s ' ')"
    is_cmd "$cmd" || return 1
    local -a new_history
    new_history=( "$cmd" )
    for old_cmd in "${cmd_history[@]}"; do
        if [[ $old_cmd != $cmd ]]; then
            new_history+=( "$old_cmd" )
        fi
    done
    cmd_history=( "${new_history[@]}" )
    debug "add_cmd cmd_history[0]: $cmd"
}

# UP: returns previous cmd in history
function get_prev_cmd(){
    if [[ ! $ADDTMPCMD ]]; then
        debug "get_prev add tmp_cmd: $cmd"
        add_cmd "$cmd"
        ADDTMPCMD="yes"
    fi
    if [[ $history_index -lt $((${#cmd_history[@]}-1)) ]]; then
        cmd="${cmd_history[$((++history_index))]}"
        debug "get_prev cmd_history[$((history_index))]: $cmd"

        # move the cursor to the beginning to print the command selected
        [[ $pos != 1 ]] && tput cub $((pos-1)) # move cursor left to the beginning

        # print the command found in history
        echo -n "$cmd"
        tput el # clean to the end of the line
        let pos=$((${#cmd}+1))
        let len=${#cmd}
    else
        debug "get_next reached oldest cmd: $cmd"
    fi
}

# DOWN: returns next cmd in history
function get_next_cmd(){
    if [[ $history_index -gt 0 ]]; then
        cmd="${cmd_history[$((--history_index))]}"
        debug "get_next cmd_history[$((history_index))]: $cmd"

        # move the cursor to the beginning to print the command selected
        [[ $pos != 1 ]] && tput cub $((pos-1)) # move cursor left to the beginning

        # print the command found in history
        echo -n "$cmd"
        tput el # clean to the end of the line
        let pos=$((${#cmd}+1))
        let len=${#cmd}
    elif [[ ! $ENDHIST ]]; then
        debug "get_next reached newest cmd: $cmd"
        unset ADDTMPCMD
        let history_index=-1
        cmd=""
        # move the cursor to the beginning to print the command selected
        [[ $pos != 1 ]] && tput cub $((pos-1)) # move cursor left to the beginning

        tput el # clean to the end of the line
        let pos=$((${#cmd}+1))
        let len=${#cmd}
        ENDHIST=yes
    fi
}

# returns last command's path
function get_lastcmd_arg(){
    echo "${cmd_history[$((history_index+1))]}" | cut -d' ' -f2
}

# saves history to $HOME/.vclistory
function save_history(){
    > "$VCLISTORY"
    for (( idx=${#cmd_history[@]}-1 ; idx>=0 ; idx-- )) ; do
        echo "${cmd_history[$idx]}" >> "$VCLISTORY"
    done
}

# loads history from $HOME/.vclistory
function load_history(){
    [[ ! -e $VCLISTORY ]] && return
    echo -n "Loading history... "
    while read cmd; do
        add_cmd "$cmd"
    done < "$VCLISTORY"
    echo "done"
}

# loads history from $HOME/.vclistory
function print_history(){
    if [[ ${#cmd_history[@]} == 0 ]]; then
        echo "No history found"
        return
    fi
    local n=1
    local depth
    local historylines=${#cmd_history[@]}
    depth="$(( ${#historylines} - 1 ))"
    for (( idx=${#cmd_history[@]}-1 ; idx>=0 ; idx-- )) ; do
        npadded="$(printf %0"${depth}"d $n)"
        echo "#$npadded: ${cmd_history[$idx]}"
        let n++
    done
}

# return vcli commands found in history matching $cmd
function rotate_found_cmds(){
    debug "rotate_found_cmds"
    if [[ ! $search_cmd ]]; then
        search_cmd="$*"
    fi
    debug "search_next_from: $search_cmd, \$SEARCHIST: $SEARCHIST"
    if [[ ! $SEARCHIST ]]; then
        # starting vcli search mode. Build a tmp_history with all matching commands
        for (( idx=0 ; idx<=${#cmd_history[@]}-1 ; idx++ )) ; do
            if [[ "${cmd_history[$idx]}" =~ $search_cmd ]]; then
                tmp_history+=( "${cmd_history[$idx]}" )
            fi
            [[ ! $SEARCHIST ]] && SEARCHIST="0"
        done
        # print first command found
        # if another Ctrl+r is hit next item will be printed
        debug "\${#tmp_history}=${#tmp_history[@]}"
        debug "\${tmp_history[$SEARCHIST]}=\"${tmp_history[$SEARCHIST]}"\"
        cmd="${tmp_history[$SEARCHIST]}"
    else
        let SEARCHIST++
        SEARCHIST=$((SEARCHIST%(${#tmp_history[@]})))
        debug "\${#tmp_history}=${#tmp_history[@]}"
        debug "\${tmp_history[$SEARCHIST]}=\"${tmp_history[$SEARCHIST]}"\"
        cmd="${tmp_history[$SEARCHIST]}"
    fi
}
################################################# CLI FUNCTIONS #################################################


# Usage
function help(){
    cat <<EOH
Usage: $0 -v <vault_host> -p <vault_port> -t <vault_token> [-i]
EOH
}

# Print commands help
function commands_help(){
    local arg="$1"
    if [[ ! $arg ]]; then
        echo -e "available commands [mount|umount|cd|ls|tree|cptree|rmtree|backup|restore|cat|cp|getcert|certinfo|getkrb|krbinfo|mv|put|rm|history|exit]"
        return
    fi
    case $arg in
        mount)     echo -e "mount path/to/mount \n  creates mount $current_pwd/path/to/mount" ;;
        umount)    echo -e "umount path/to/mount \n  destroys mount $current_pwd/path/to/mount" ;;
        cd)        echo -e "cd path/to/secret \n  changes to directory $current_pwd/path/to/secret" ;;
        ls)        echo -e "ls path/to/secret \n  lists paths and keys on $current_pwd/path/to/secret" ;;
        tree)      echo -e "tree path/to/secret \n  prints vault's secrets tree with $current_pwd/path/to/secret as its root" ;;
        cptree)    echo -e "cptree path/to/secret path/to/other_secret \n  copies tree to destination path $current_pwd/path/to/other_secret" ;;
        rmtree)    echo -e "rmtree path/to/secret \n  removes path $current_pwd/path/to/secret recursively" ;;
        backup)    echo -e "backup \n  backs up Vault to $TMP folder" ;;
        restore)   echo -e "restore \n  restores Vault backup" ;;
        cat)       echo -e "cat path/to/secret \n  shows contents of key $current_pwd/path/to/secret" ;;
        cp)        echo -e "cp path/to/secret path/to/other_secret \n  copies contents of path to path $current_pwd/path/to/other_secret" ;;
        getcert)   echo -e "getcert path/to/secret \n  downloads certificate CRT and KEY stored in $current_pwd/path/to/secret" ;;
        certinfo)  echo -e "certinfo path/to/secret \n  shows certificate info stored in $current_pwd/path/to/secret" ;;
        getkrb)    echo -e "getkrb path/to/secret \n  exports keytab file to $TMP/principal.keytab" ;;
        krbinfo)   echo -e "krbinfo path/to/secret \n  shows principal & keytab info stored in $current_pwd/path/to/secret" ;;
        mv)        echo -e "mv path/to/secret path/to/other_secret \n  moves contents of path to path $current_pwd/path/to/other_secret" ;;
        put)       echo -e "put path/to/secret { \"key\": \"value\" } \n  adds json={ \"key\": \"value\" } to $current_pwd/path/to/secret" ;;
        rm)        echo -e "rm path/to/secret \n  removes key $current_pwd/path/to/secret" ;;
        history)   echo -e "history \n  shows vcli history" ;;
        exit)      echo -e "exit \n  exits vcli" ;;
        *)         echo -e "unkown '$arg' vcli command\navailable commands [mount|umount|cd|ls|tree|cptree|rmtree|backup|restore|cat|cp|getcert|certinfo|getkrb|krbinfo|mv|put|rm|history|exit]" ;;
    esac
}

# Check for given arguments
function check_arg(){
    local arg=$1
    local msg=$2
    if [[ ! $arg ]]; then
        echo -e "ERROR! No $msg provided\n"
        help ; exit 1
    fi
}

# save & clean & exit
function clean_n_exit(){
    save_history
    echo
    # reset terminal when running inside a container as local echo gets disabled (??)
    if ! head -n 1 /proc/1/sched | grep -qE "(systemd|init)"; then
        reset
    fi
    exit
}

# Run command and prettyfy stdout
function _run(){
    local exit_status
    if [[ $VERBOSE == yes ]]; then
        local tmp
        tmp=$(mktemp -p /dev/shm -t .run.XXXX)
        eval "$*" 2> "$tmp" # store stderr in $tmp
        exit_status=$?
        while IFS=$'\n' read line; do
            echo "      > $line"
        done < "$tmp"
        rm -f "$tmp"
    else
        eval "$*" 2> /dev/null
        exit_status=$?
    fi
    return $exit_status
}

# simplified curl function
function _curl(){
    local enable_f="-f"
    if [[ "$1" == "-_disable_-f_-" ]]; then
        unset enable_f
        shift
    elif [[ "$1" == "-i" ]]; then
        local ignore_http_code="true"
        shift
    fi
    local endpoint="${1#/}" # remove initial '/' if exists
    local data="$2"
    local response
    if [[ "$data" == "-_list_root_-" ]]; then
        ROOT_QUERY="yes"
    fi
    # POST, GET, PUT, PATCH, DELETE
    # http://www.restapitutorial.com/lessons/httpmethods.html
    local method="${3:-GET}"
    debug "curl: _curl '$1' '$2' '$3'"
    if [[ $data ]]; then
        if [[ "$VERBOSE" = "yes" ]]; then
            echo -e "url: $protocol://$vault_host:$vault_port/v1/$endpoint\nmethod: $method\ndata:$data"
        fi
        mapfile -t response < <(_run "/usr/bin/curl -w \"%{http_code}\n\" -s $enable_f -k -L -X$method -H \"X-Vault-Token:$vault_token\" \
                      -H 'Content-type: application/json' \
                      -d \"$data\" \
                      \"$protocol://$vault_host:$vault_port/v1/$endpoint\"")
    else
        if [[ "$VERBOSE" = "yes" ]]; then
            echo -e "url: $protocol://$vault_host:$vault_port/v1/$endpoint\nmethod: $method"
        fi
        mapfile -t response < <(_run "/usr/bin/curl -w \"%{http_code}\n\" -s $enable_f -k -L -X$method -H \"X-Vault-Token:$vault_token\" \
                      -H 'Content-type: application/json' \
                      \"$protocol://$vault_host:$vault_port/v1/$endpoint\"")
    fi
    #debug "response_mapfile: ${response[0]} # ${response[1]}"
    if [[ ! "$ignore_http_code" ]]; then
        if [[ ! ${response[1]} ]]; then
            http_code="${response[0]}"
        else
            if [[ $ROOT_QUERY ]]; then
                echo "${response[0]}" | jq '.data | keys'
            else
                echo "${response[0]}" | jq ''
            fi
            http_code="${response[1]}"
        fi
        if [[ ! "$http_code" =~ ^2 ]]; then
            return 1
        fi
    fi
    unset ROOT_QUERY response
}

# run command entered in CLI
function run_cmd(){
    local cmd="$*"
    while IFS=$' ' read cmd arg1 arg2; do
        if [[ $arg1 == "!$" ]]; then
            arg1=$(get_lastcmd_arg)
        fi
        case $cmd in
            cd)                     _cd "$arg1" ;;
            ls)                     _ls "$arg1" ;;
            tree)                   backIFS=$IFS; IFS=$' ' ; _tree "$arg1" ; IFS=$backIFS;;
            cptree)                 backIFS=$IFS; IFS=$' ' ; _cptree "$arg1" "$arg2" ; IFS=$backIFS;;
            rmtree)                 backIFS=$IFS; IFS=$' ' ; _rmtree "$arg1" ; IFS=$backIFS;;
            backup)                 backIFS=$IFS; IFS=$' ' ; _backup "/" ; IFS=$backIFS;;
            restore)                backIFS=$IFS; IFS=$' ' ; _restore "$arg1" ; IFS=$backIFS;;
            cat)                    _cat "$arg1" ;;
            put)                    _put "$arg1" "$arg2" ;;
            rm)                     _rm "$arg1" ;;
            cp)                     _cp "$arg1" "$arg2" ;;
            getcert)                _getcert "$arg1" ;;
            certinfo)               _certinfo "$arg1" ;;
            getkrb)                 _getkrb "$arg1" ;;
            krbinfo)                _krbinfo "$arg1" ;;
            mv)                     _mv "$arg1" "$arg2" ;;
            mount)                  _mount "$arg1" ;;
            umount)                 _umount "$arg1" ;;
            history)                print_history ;;
            exit)                   save_history; exit ;;
            help)                   commands_help "$arg1" ;;
            enable-debug)           echo "debug enabled" ; DEBUG="yes";;
            disable-debug)          echo "debug disabled" ; DEBUG="no";;
            enable-hexdump-debug)   echo "hexdump debug enabled" ; DEBUG_HEXDUMP="yes";;
            disable-hexdump-debug)  echo "hexdump debug disabled" ; DEBUG_HEXDUMP="no";;
            \#*)                    return;; # ignore commented lines
            *)                      commands_help "$cmd" ; return 1 ;;
        esac
        debug "run_cmd: $cmd $arg1 $arg2"
        debug "http_code=$http_code"
        add_cmd "$cmd $arg1 $arg2"
    done< <(echo "$cmd")
}

# mount function
function _mount(){
    if [[ "$1" == "-i" ]]; then
        local ignore_http_code="true"
        shift
    fi
    local url="$1"
    local data
    if [[ ! $url ]]; then
        echo "mounted paths:"
        for path in "${mounted_paths[@]}"; do
            if [[ $path ]]; then
                echo "$path"
            fi
        done
    # mount $url
    else
        # get full path if relative reference
        if [[ ! "$url" =~ ^/ ]]; then
            url="/sys/mounts/$current_pwd$url"
        else
            url="/sys/mounts$url"
        fi
        # check if already mounted in this session
        if [[ ! "${mounted_paths[@]}" =~ $url ]]; then
            data="{ \\\"type\\\": \\\"generic\\\", \\\"description\\\": \\\"$url secret backend\\\" }"
            if [[ $ignore_http_code ]]; then
                _curl -i "$url" "$data" "POST"
            else
                _curl "$url" "$data" "POST"
            fi
            mounted_paths+=( "$url" )
            echo "mounted '$url'"
        else
            echo "'$url' already mounted in this session."
        fi
    fi
}

# umount function
function _umount(){
    if [[ "$1" == "-i" ]]; then
        local ignore_http_code="true"
        shift
    fi
    local url="$1"
    if [[ ! $url ]]; then
        echo "umount needs an argument"
        _mount
    fi
    # get full path if relative reference
    if [[ ! "$url" =~ ^/ ]] && [[ ! "$url" =~ ^/sys/mounts ]]; then
        url="/sys/mounts/$current_pwd$url"
    elif [[ ! "$url" =~  ^/sys/mounts ]]; then
        url="/sys/mounts$url"
    fi
    if [[ $ignore_http_code ]]; then
        _curl -i "$url" "" "DELETE"
    else
        _curl "$url" "" "DELETE"
    fi
    mounted_paths=( "${mounted_paths[@]/$url}" ) # delete mounted mountpoint
}

# cd function
function _cd(){
    local url="$1"
    if [[ $url == ".." ]]; then
        url=${current_pwd%*/}
        url=${url%/*}/
    elif [[ $url =~ ^/ ]]; then
        : # do nothing url is perfect as it is
    elif [[ $url ]]; then
        url="$current_pwd/$url/"
        url=${url//\/\//\/}
    elif [[ $current_pwd ]]; then
        url="$current_pwd/"
        url=${url//\/\//\/}
    else
        current_pwd="/"
    fi
    if [[ $url != "/" ]] && [[ "$1" != ".." ]] && ! _ls "$url" | grep -q "request_id"; then
        echo "Error! '$url' not found"
    elif [[ $url != "/" ]]; then
        current_pwd="$url"
    else
        current_pwd=""
    fi
    debug "cd: cd $1 ; current_pwd=$current_pwd"
}

# ls function
function _ls(){
    local url
    if [[ ! $1 =~ ^/ ]]; then
        url="$current_pwd/$1"
    else
        url="$1"
    fi
    if [[ $url == '/' ]]; then
        _cat /sys/mounts "-_list_root_-"
        return
    elif [[ $url ]]; then
        url="$url?list=true"
    else
        url="$current_pwd?list=true"
    fi
    _curl "$url"
}

function padecho(){
    local msg="$1"
    local depth="$2"
    local space="$3"
    local echospace="$4"
    # we print 2 spaces for every depth
    for (( i=${#space} ; i<$((depth*2)) ; i++ )) ; do
        # if is folder
        echo -n " "
    done
    msg=${msg/\/\//\/}
    msg=${msg//\//$CYAN\/$NONE}
    space=${space//+/$CYAN+$NONE}
    space=${space//\`/$CYAN\`$NONE}
    debug "${echospace}msg: $msg, depth: $depth ; space: \"$space\""
    echo "$space$msg"
}

# display the vault's secret tree
function _tree(){
    local url
    if [[ ! $1 =~ ^/ ]]; then
        url="$current_pwd$1"
    else
        url="$(echo "$1" | tr -s '/')"
    fi
    local depth="$2"
    local space="$3"
    local echo_space="$4"
    # If no "$2" was passed then this iteration is the very first one, so depth=0
    if [[ ! $depth ]]; then
        depth=0
    # other wise we increment a depth as we go deeper in the structure
    else
        let depth++
    fi
    debug "${echo_space}tree: '$url', depth: $depth, space: \"$space\""
    # if $url is /
    padecho "$(basename "$url")/" "$depth" "$space" "$echo_space   "
    if [[ $url == "/" ]] || [[ ! $url ]]; then
        paths=$(_ls "$url" | grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    # if $url is other than root
    else
        paths=$(_ls "$url" | jq '.data .keys' |grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    fi

    for path in $paths; do
        debug "${echo_space}   depth: $depth => found: $paths"
        space=${space/+/ }
        if [[ $path =~ /$ ]]; then
            _tree "$url/$path" "$depth" "$space+ " "$echo_space   "
        else
            padecho "$path" "$((depth+1))" "$space\` " "$echo_space   "
        fi
    done
}

# backup vault
function _backup(){
    local url
    if [[ ! $1 =~ ^/ ]]; then
        url="$current_pwd$1"
    else
        url="$(echo "$1" | tr -s '/')"
    fi
    local first
    local dest="$2"
    local depth="$3"
    local space="$4"
    local echo_space="$5"
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "backup"
        return
    fi
    if [[ ! $dest ]]; then
        dest="$(mktemp -d -p /dev/shm -t backup_vault-"$(date +%d-%m-%Y@%H:%M:%S)".XXXX)"
        destfile="$TMP/backup_vault.$(date +%d-%m-%Y@%H:%M:%S).tgz"
    fi
    # If no depth was passed then this iteration is the very first one, so depth=0
    if [[ ! $depth ]]; then
        depth=0
        first="yes"
        echo -n "Backing up Vault to '$destfile'"
    # other wise we increment a depth as we go deeper in the structure
    else
        unset first
        let depth++
    fi
    debug "${echo_space}backup: '$url', depth: $depth, space: \"$space\""
    # if $url is /
    #padecho "$(basename "$url")/" "$depth" "$space" "$echo_space   "
    if [[ $url == "/" ]] || [[ ! $url ]]; then
        paths=$(_ls "$url" | grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    # if $url is other than root
    else
        paths=$(_ls "$url" | jq '.data .keys' |grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    fi

    debug "${echo_space}   depth: $depth => found: $paths"
    for path in $paths; do
        space=${space/+/ }
        if [[ $path =~ /$ ]]; then
            local _path="$url/$path"
            _path=${_path//\/\//\/}
            _backup "$_path" "$dest" "$depth" "$space+ " "$echo_space   "
        else
            local _dest=${url#*/}
            mkdir -p "$dest/$_dest"
            _cat "$url$path" | jq '.data' > "$dest/$_dest$path"
            echo -n "."
        fi
    done
    if [[ $first ]]; then
        cd "$dest"
        tar cfz "$destfile" ./* > /dev/null
        echo " done"
    fi
}

# restore vault backup
function _restore(){
    local backup folder mount _url
    backup="$1"
    if [[ ! -r $backup ]]; then
        echo "Error! Missing backup file"
        commands_help "restore"
        return
    fi
    local first
    local folder="$2"
    local _url="$3"
    local depth="$4"
    local space="$5"
    local echo_space="$6"
    # If no depth was passed then this iteration is the very first one, so depth=0
    if [[ ! $depth ]]; then
        depth=0
        first="yes"
        echo -n "Restoring Vault backup from '$backup'"
        folder="$(mktemp -d -p /dev/shm -t backup_vault-"$(date +%d-%m-%Y@%H:%M:%S)".XXXX)"
        cd "$folder"
        if ! tar xfz "$backup" > /dev/null 2>&1; then
            echo "Error while extracting backup '$backup'"
            rm -fr "$folder"
            return
        fi
    # other wise we increment a depth as we go deeper in the structure
    else
        unset first
        let depth++
        cd "$folder"
    fi
    debug "${echo_space}restore: '$backup', folder: $folder, _url: $_url depth: $depth, space: \"$space\""
    paths=$(find . -maxdepth 1 -not -iname "." | tr -t '\n' ' ')

    debug "${echo_space}   depth: $depth => found: $paths"
    for path in $paths; do
        path=${path/.\/}
        space=${space/+/ }
        if [[ -d $path ]]; then
            mount=$(echo "$_url" | sed -e "s/^\(\/[^/]\+\).*$/\1/")
            if [[ $mount ]]; then
                debug "${echo_space}   mount: $mount"
                _mount -i "$mount" > /dev/null 2>&1
            fi
            _restore "$backup" "$PWD/$path" "$_url/$path" "$depth" "$space+ " "$echo_space   "
        else
            debug "${echo_space}   put $_url/$path $(tr -d '\n' < "$PWD/$path" | tr -s ' ')"
            _put "$_url/$path" "$(tr -d '\n' < "$PWD/$path" | tr -s ' ')"
            echo -n "."
        fi
    done
    if [[ $first ]]; then
        echo " done"
    else
        cd ..
    fi
}

# copy secret tree to another location
function _cptree(){
    local url
    if [[ ! $1 =~ ^/ ]]; then
        url="$current_pwd$1"
    else
        url="$(echo "$1" | tr -s '/')"
    fi
    local first
    local dest="$2"
    local depth="$3"
    local space="$4"
    local echo_space="$5"
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "cptree"
        return
    fi
    if [[ ! $dest ]]; then
        echo "Error! Missing destination"
        commands_help "cptree"
        return
    fi
    # If no "$2" was passed then this iteration is the very first one, so depth=0
    if [[ ! $depth ]]; then
        depth=0
        first="yes"
        echo -n "Copying tree from '$url' to '$dest'"
    # other wise we increment a depth as we go deeper in the structure
    else
        unset first
        let depth++
    fi
    debug "${echo_space}cptree: '$url', depth: $depth, space: \"$space\""
    # if $url is /
    #padecho "$(basename "$url")/" "$depth" "$space" "$echo_space   "
    if [[ $url == "/" ]] || [[ ! $url ]]; then
        paths=$(_ls "$url" | grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    # if $url is other than root
    else
        paths=$(_ls "$url" | jq '.data .keys' |grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    fi

    for path in $paths; do
        debug "${echo_space}   depth: $depth => found: $paths"
        space=${space/+/ }
        if [[ $path =~ /$ ]]; then
            local _path="$url/$path"
            _path=${_path//\/\//\/}
            _cptree "$_path" "$dest" "$depth" "$space+ " "$echo_space   "
        else
            _mount -i "$dest" > /dev/null 2>&1
            local _dest=${url#*/}
            _cp "/$url$path" "/$dest/$_dest$path"
            echo -n "."
        fi
    done
    if [[ $first ]]; then
        echo " done"
    fi
}

# removes recursively a vault path
function _rmtree(){
    local url
    if [[ ! $1 =~ ^/ ]]; then
        url="$current_pwd$1"
    else
        url="$(echo "$1" | tr -s '/')"
    fi
    local first
    local depth="$2"
    local space="$3"
    local echo_space="$4"
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "rmtree"
        return
    fi
    # If no "$2" was passed then this iteration is the very first one, so depth=0
    if [[ ! $depth ]]; then
        depth=0
        first="yes"
        echo -n "Removing recursively '$url'"
    # other wise we increment a depth as we go deeper in the structure
    else
        let depth++
    fi
    debug "${echo_space}rmtree: '$url', depth: $depth, space: \"$space\""
    # if $url is /
    #padecho "$(basename "$url")/" "$depth" "$space" "$echo_space   "
    if [[ $url == "/" ]] || [[ ! $url ]]; then
        paths=$(_ls "$url" | grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    # if $url is other than root
    else
        paths=$(_ls "$url" | jq '.data .keys' |grep "\"" | sed -e "s/\"//g" -e "s/,//" | tr -t '\n' ' ' | tr -s ' ')
    fi

    for path in $paths; do
        debug "${echo_space}   depth: $depth => found: $paths"
        space=${space/+/ }
        if [[ $path =~ /$ ]]; then
            local _path="$url/$path"
            _path=${_path//\/\//\/}
            _rmtree "$_path" "$depth" "$space+ " "$echo_space   "
        else
            _rm "/$url$path"
            echo -n "."
        fi
    done
    if [[ $first ]]; then
        _umount -i "$url" > /dev/null 2>&1
        echo " done"
    fi
}

# cat function
function _cat(){
    if [[ "$1" == "-_disable_-f_-" ]]; then
        disable_f="$1"
        shift
    fi
    local url="$1"
    if [[ ! $url =~ ^/ ]]; then
        url="$current_pwd$1"
    fi
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "cat"
        return
    fi
    debug "cat: url=$url"
    local arg="$2"
    _curl $disable_f "$url" "$arg"
}

# cp function
function _cp(){
    local url="$1"
    local dest="$2"
    if [[ ! $url =~ ^/ ]]; then
        url="$current_pwd$url"
    fi
    if [[ ! $dest =~ ^/ ]]; then
        dest="$current_pwd$dest"
    fi
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "cp"
        return
    fi
    if [[ ! $dest ]]; then
        echo "Error! Missing destination"
        commands_help "cp"
        return
    fi
    debug "cp: url=$url dest=$dest"
    secret=$(_cat "$url" | jq ".data" )
    debug "$secret"
    _put "$dest" "$secret"
}

# mv function
function _mv(){
    local url="$1"
    local dest="$2"
    if [[ ! $url =~ ^/ ]]; then
        url="$current_pwd$url"
    fi
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "mv"
        return
    fi
    if [[ ! $dest =~ ^/ ]]; then
        dest="$current_pwd$dest"
    fi
    if [[ ! $dest ]]; then
        echo "Error! Missing destination"
        commands_help "mv"
        return
    fi
    debug "mv: url=$url dest=$dest"
    _cp "$url" "$dest" && _rm "$url"
}

# rm function
function _rm(){
    local url="$1"
    if [[ ! $url =~ ^/ ]]; then
        url="$current_pwd$1"
    fi
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "rm"
        return
    fi
    debug "rm: url=$url"
    _curl "$url" "" "DELETE"
}

# put function
function _put(){
    local url="$1"
    if [[ ! $url =~ ^/ ]]; then
        url="$current_pwd$1"
    fi
    debug "put: url=$url"
    local data=${2//\"/\\\"}
    if [[ ! $url ]]; then
        echo "Error! Missing secret path"
        commands_help "put"
        return
    fi
    if [[ ! $data ]]; then
        echo "Error! Missing secret data"
        commands_help "put"
        return
    fi
    url="${url/\/\//\/}"
    debug "$data"
    debug "uploading '$data' to '$url'"
    _curl "$url" "$data" "POST"
}

# validate and show principals and keytab info
function _krbinfo(){
    local url="$1"
    local certs tmp
    # Get principals and store them in ${princs[@]}
    declare -A princs
    if [[ ! $url ]]; then
        echo "Error! Missing keytab path"
        commands_help "krbinfo"
        return
    fi
    _cat "$url" > /dev/null 2>&1
    eval "$(_cat "$url" | jq ".data | to_entries | map(select(.key | match(\"$pri_suffix\"))) | map(\"princs[\(.key)]=\\\"\(.value|tostring)\\\"\") | .[] | @sh" | sed -e "s/^\"//" -e "s/\"$//" -e "s/^'//" -e "s/'$//" -e "s/$pri_suffix//")"
    backIFS=$IFS
    IFS=$' '
    keys=$(echo "${!princs[@]}" | tr -t ' ' '\n' | sort | tr -t '\n' ' ')
    for key in $keys ; do
        value=${princs[$key]}
        key="\"${key}_keytab\""
        tmp=$(mktemp -p /dev/shm -t .krbinfo.XXXX)
        _cat "$url" | jq ".data .${key}" | tr -d '"' | base64 -d > "$tmp"
        echo -en "\n${BOLD}principal$NONE: $CYAN${value//\"/}$NONE"
        if ! klist -kt "$tmp" | grep -v "Keytab name:" | grep -q "${value//\"/}"; then
            echo -e " ${RED}NOT FOUND${NONE} ${BOLD}in keytab!${NONE}"
        else
            echo
        fi
        klist -kte "$tmp" | grep -v "Keytab name:"
        rm -f "$tmp"
    done
    IFS=$backIFS
}

# download keytab to /tmp
function _getkrb(){
    local url="$1"
    local certs tmp
    # Get principals and store them in ${princs[@]}
    declare -A princs
    if [[ ! $url ]]; then
        echo "Error! Missing keytab path"
        commands_help "getkrb"
        return
    fi
    _cat "$url" > /dev/null 2>&1
    eval "$(_cat "$url" | jq ".data | to_entries | map(select(.key | match(\"$pri_suffix\"))) | map(\"princs[\(.key)]=\\\"\(.value|tostring)\\\"\") | .[] | @sh" | sed -e "s/^\"//" -e "s/\"$//" -e "s/^'//" -e "s/'$//" -e "s/$pri_suffix//")"
    backIFS=$IFS
    IFS=$' '
    keys=$(echo "${!princs[@]}" | tr -t ' ' '\n' | sort | tr -t '\n' ' ')
    echo "Exporting keytabs..."
    for key in $keys ; do
        value=${princs[$key]}
        value=${value//\"/}
        key="\"${key}_keytab\""
        tmp=$(mktemp -p /dev/shm -t .getkrb.XXXX)
        _cat "$url" | jq ".data .${key}" | tr -d '"' | base64 -d > "$tmp"
        echo "  - ${value} exported to '$TMP/${value//\//_}.keytab'"
        cp "$tmp" "$TMP/${value//\//_}.keytab"
        rm -f "$tmp"
    done
    echo "done."
    IFS=$backIFS
}

# validate that crt and key match and show certificate info
function _certinfo(){
    local url="$1"
    local CRT KEY secret
    if [[ ! $url ]]; then
        echo "Error! Missing cert path"
        commands_help "certinfo"
        return
    fi
    local certs cert shacrt keys key shakey
    _cat "$url" > /dev/null 2>&1
    backIFS=$IFS
    IFS=$' '
    certs=( $(_cat "$url" | jq ".data | to_entries | map(select(.key | match(\"$crt_suffix\"))) | .[] .key" | tr -t '\n' ' ' | sort) )
    keys=( $(_cat "$url" | jq ".data | to_entries | map(select(.key | match(\"$key_suffix\"))) | .[] .key" | tr -t '\n' ' ' | sort) )
    for ((n=0;n<${#certs[@]};n++)); do
        cert=${certs[$n]}
        key=${keys[$n]}
        debug "_cat $url | jq .data .$cert"
        secret=$(_cat "$url")
        CRT=$(echo -e "$secret" | jq ".data .$cert" | \
                      sed -e 's/-----BEGIN CERTIFICATE-----/-----BEGIN CERTIFICATE-----\n/g' \
                          -e 's/-----END CERTIFICATE-----/\n-----END CERTIFICATE-----/g' \
                          -e 's/-----END CERTIFICATE----------BEGIN CERTIFICATE-----/-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----/g' | fold -64 | tr -d '"')
        KEY=$(echo -e "$secret" | jq ".data .$key" | \
                      sed -e 's/-----BEGIN RSA PRIVATE KEY-----/-----BEGIN RSA PRIVATE KEY-----\n/g' \
                          -e 's/-----END RSA PRIVATE KEY-----/\n-----END RSA PRIVATE KEY-----/g' | fold -64 | tr -d '"')
        shacrt=$(echo -e "$CRT" | openssl x509 -pubkey -noout -outform pem | sha256sum)
        shakey=$(echo -e "$KEY" | openssl pkey -pubout -outform pem | sha256sum)
        echo -en "\n${BOLD}certificate${NONE}: $CYAN${cert//\"/}${NONE}"
        if [[ "$shacrt" != "$shakey" ]]; then
            echo -e " ${RED}DOESN'T MATCH${NONE} ${BOLD}${key//\"/}${NONE}"
        else
            echo
        fi
        echo -e "$CRT" | openssl x509 -text -noout
    done
    IFS=$backIFS
}

# download certificates crt and key
function _getcert(){
    local url="$1"
    local CRT KEY secret
    if [[ ! $url ]]; then
        echo "Error! Missing cert path"
        commands_help "getcert"
        return
    fi
    local certs cert keys key
    _cat "$url" > /dev/null 2>&1
    backIFS=$IFS
    IFS=$' '
    certs=( $(_cat "$url" | jq ".data | to_entries | map(select(.key | match(\"$crt_suffix\"))) | .[] .key" | tr -t '\n' ' ' | sort) )
    keys=( $(_cat "$url" | jq ".data | to_entries | map(select(.key | match(\"$key_suffix\"))) | .[] .key" | tr -t '\n' ' ' | sort) )
    echo "Exporting certificates..."
    for ((n=0;n<${#certs[@]};n++)); do
        cert=${certs[$n]}
        key=${keys[$n]}
        debug "_cat $url | jq .data .$cert"
        secret=$(_cat "$url")
        CRT=$(echo -e "$secret" | jq ".data .$cert" | \
                      sed -e 's/-----BEGIN CERTIFICATE-----/-----BEGIN CERTIFICATE-----\n/g' \
                          -e 's/-----END CERTIFICATE-----/\n-----END CERTIFICATE-----/g' \
                          -e 's/-----END CERTIFICATE----------BEGIN CERTIFICATE-----/-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----/g' | fold -64 | tr -d '"')
        KEY=$(echo -e "$secret" | jq ".data .$key" | \
                      sed -e 's/-----BEGIN RSA PRIVATE KEY-----/-----BEGIN RSA PRIVATE KEY-----\n/g' \
                          -e 's/-----END RSA PRIVATE KEY-----/\n-----END RSA PRIVATE KEY-----/g' | fold -64 | tr -d '"')
        cert=${cert//\"/}
        key=${key//\"/}
        echo -e "  - ${cert} exported to '$TMP/${cert//_crt/}.crt'"
        echo -e "$CRT" > "$TMP/${cert//_crt/}.crt"
        echo -e "  - ${key} exported to '$TMP/${key//_key/}.key'"
        echo -e "$KEY" > "$TMP/${key//_key/}.key"
    done
    IFS=$backIFS
    echo "done."
}

# main function
function main(){
    # First of all: check command dependencies
    check_dependency "$DEPENDENCIES"

    local tmpmsg
    protocol="https"
    while getopts "v:p:t:hi" opt; do
        case $opt in
            v) vault_host=$OPTARG ;;       ### GLOBAL VARIABLES ###
            p) vault_port=$OPTARG ;;       ### GLOBAL VARIABLES ###
            t) vault_token=$OPTARG ;;      ### GLOBAL VARIABLES ###
            i) protocol="http";;
            h|*) help ; exit 1; ;;
        esac
    done

    # Use VAULT_ADDR as the primary default as it is the most common setting.
    # If VAULT_ADDR is set it will overwrite VAULT_HOST and VAULT_PORT
    if [[ $VAULT_ADDR ]] && [[ $VAULT_ADDR =~ ^http[s]*://[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+ ]]; then
        protocol=${VAULT_ADDR%%:*}
        local host_port=${VAULT_ADDR#*//}
        VAULT_HOST=${host_port%:*}
        VAULT_PORT=${host_port#*:}
    fi

    # Use environment variables VAULT_HOST VAULT_TOKEN and VAULT_PORT if defined
    vault_port=${VAULT_PORT:-"$vault_port"}
    vault_port=${vault_port:-"8200"} # Define Vault default port if not specified
    vault_host=${VAULT_HOST:-$vault_host}
    vault_token=${VAULT_TOKEN:-$vault_token}

    # Check for correct arguments
    check_arg "$vault_host" "Vault host"
    check_arg "$vault_token" "Vault token"

    # Check connectivity
    check_connectivity

    # BEGIN
    # initialize variables
    len=0
    pos=1
    history_index=-1

    # try to get vault health status
    _put secret/-_test_- '{ "key": "value" }'
    if ! _cat secret/-_test_- > /dev/null 2>&1 ; then
        echo -e "Cannot access vault's secrets!\nCheck vault_token: '$vault_token'"
        exit 1
    else
        _rm secret/-_test_-
    fi

    # load vcli history
    load_history

    # Show vault's health
    _cat "-_disable_-f_-" sys/health

    # print prompt
    prompt

    # trap for Ctrl+c
    trap clean_n_exit INT

    # Begin iteration
    IFS=
    while true; do
        lastkey=$key
        # read key and process
        read -sN1 key
        case $key in
            $'\x1b')
                read -rsn1 -t 0.001 key # flush read
                if [[ $key == "[" ]]; then # CURSORS & SPECIAL CHARS
                    read -rsn1 -t 0.001 key # flush read again
                    case $key in
                        $'\x41') # up cursor: older history
                            get_prev_cmd
                        ;;
                        $'\x42') # down cursor: newer history
                            get_next_cmd
                        ;;
                        $'\x43') # right cursor
                            if [[ $pos -lt $((len+1)) ]]; then # if anything was typed allow to move cursor left
                                tput cuf 1 # move cursor right
                                let pos+=1 # increment cursor position
                                debug "pos: $pos right"
                            fi
                        ;;
                        $'\x44') # left cursor
                            if [[ $pos -gt 1 ]]; then # if anything was typed and position>0 allow to move cursor left
                                tput cub 1 # move cursor left
                                let pos-=1 # decrement cursor position
                                debug "pos: $pos left"
                            fi
                        ;;
                    esac
                elif [[ $key == "O" ]]; then # HOME & END KEYS
                    read -rsn1 -t 0.001 key # flush read again
                    case $key in
                        $'\x46') # END
                                [[ $len != 0 ]] && tput cuf $((len-pos+1)) # move cursor right to the end
                                let pos=len+1
                        ;;
                        $'\x48') # HOME
                                [[ $len != 0 ]] && tput cub $((pos-1)) # move cursor left to the beginning
                                let pos=1
                        ;;
                    esac
                fi
                unset ENDHIST
            ;;
            $'\x0a') # ENTER
                unset ENDHIST
                is_command="true"
                debug "current_pwd=$current_pwd"
                echo
                if [[ $cmd ]] && [[ ! "$cmd" =~ ^[[:space:]]+$ ]]; then
                    cmd=$(echo "$cmd" | sed -e "s/^[[:space:]]\+\(.*\)/\1/g" -e "s/[[:space:]]\+$//g" | tr -s ' ')
                    run_cmd "$cmd"
                fi
            ;;
            $'\x7f') # BACKSPACE
                unset ENDHIST
                if [[ $len != 0 ]] && [[ $pos -gt 1 ]]; then # if anything was typed and position>0 allow to delete
                    echo -en "\b \b"
                    let len-=1
                    let pos-=1
                    tmpmsg="${#cmd}: \"$cmd\""
                    # remove $key in $((pos-1))
                    cmd="${cmd:0:$((pos-1))}${cmd:$((pos)):${#cmd}}"
                    tput el # clean to the end of the line
                    restcmd="${cmd:$((pos-1)):${#cmd}}"
                    echo -n "$restcmd"
                    # reposition cursor after backspace only if we moved chars
                    if [[ ${#restcmd} != 0 ]]; then tput cub ${#restcmd} ; fi
                    debug "$tmpmsg => ${#cmd}: \"$cmd\""
                    debug "pos: $pos, len: $len"
                fi
            ;;
            $'\x7e') # ERASE
                unset ENDHIST
                if [[ $len != 0 ]] && [[ $pos -lt $((len+1)) ]]; then # if anything was typed and position>0 allow to delete
                    tput ech 1 # erase 1 character at $pos
                    let len-=1
                    tmpmsg="${#cmd}: \"$cmd\""
                    cmd=${cmd:0:$((pos-1))}${cmd:${pos}:$((${#cmd}-1))}
                    tput el # clean to the end of the line
                    #cmd=${cmd::-1} # delete last character
                    restcmd="${cmd:$((pos-1)):$((${#cmd}))}"
                    echo -n "$restcmd"
                    # reposition cursor after backspace only if we moved chars
                    if [[ ${#restcmd} != 0 ]]; then tput cub ${#restcmd} ; fi
                    debug "$tmpmsg => ${#cmd}: \"$cmd\""
                    debug "pos: $pos, len: $len"
                fi
            ;;
            $'\x09') # tab completions
                completion "$cmd"
                exit_status=$?

                if [[ $exit_status == 0 ]]; then
                    # move the cursor to the beginning to print the command selected
                    [[ $pos != 1 ]] && tput cub $((pos-1)) # move cursor left to the beginning

                    # print the command found in history
                    len=0
                    pos=1
                    tput el # clean to the end of the line
                    echo -n "$cmd"
                    tput el # clean to the end of the line
                    let len=${#cmd}
                    let pos=len+1
                else
                                        # print the command found in history
                    len=0
                    pos=1
                    tput el # clean to the end of the line
                    echo -n "$cmd"
                    tput el # clean to the end of the line
                    let len=${#cmd}
                    let pos=len+1
                fi
            ;;
            $'\x12') # Ctrl+r
                if [[ ! $cmd ]]; then
                    # clean line
                    echo -e "\nvcli hint: hit Ctrl+r when typing command to search the vcli history"
                    print_history
                    is_command="true"
                else
                    rotate_found_cmds "$cmd"
                    debug "search_cmd: $search_cmd, \$SEARCHIST: $SEARCHIST"


                    # move the cursor to the beginning to print the command selected
                    [[ $pos != 1 ]] && tput cub $((pos-1)) # move cursor left to the beginning

                    # print the command found in history
                    echo -n "$cmd"

                    tput el # clean to the end of the line
                    let pos=$((${#cmd}+1))
                    let len=${#cmd}
                fi
            ;;
            $'\x04') # Ctrl+d behaviour is the same as Ctrl+c
                clean_n_exit
            ;;
            $'\x20'|*) # NORMAL CHARS
                tput ich 1 # insert chars rather than overwriting them
                echo -n "$key" #| hexdump -C
                let len+=1
                let pos+=1
                tmpmsg="${#cmd}: \"$cmd\""
                # insert $key in $pos within $cmd string
                cmd="${cmd:0:$((pos-2))}$key${cmd:$((pos-2)):${#cmd}}"
                debug " => ${#cmd}: \"$cmd\""
                debug "pos: $pos, len: $len"
            ;;
        esac
        # Exit history search mode
        if [[ "$key" != $lastkey ]] && [[ "$key" != $'\x12' ]]; then
            debug "exiting history search mode"
            unset SEARCHIST search_cmd tmp_history
        fi
        [[ $DEBUG_HEXDUMP == "yes" ]] && debug "\nhexdump: \n $(echo -n "$key" | hexdump -C)"
        # print prompt if commadn was run
        if [[ $is_command ]]; then prompt ; unset is_command cmd pos len ; history_index=-1 ; pos=1; fi
    done
}

main "$@"
